Edit the nsvmlinux tree in the mvm build script, not the mkvmarchives script. Make uploadvms check for the NS .dmg and .msi
git-svn-id: http://squeakvm.org/svn/squeak/branches/Cog@2542 fa1542d4-bde8-0310-ad64-8ed1123d492a

Former-commit-id: a02f879237c08c7be69ff42c700c00d469b3ce44

diff --git a/nscogbuild/unixbuild/bld/mvm b/nscogbuild/unixbuild/bld/mvm
--- a/nscogbuild/unixbuild/bld/mvm
+++ b/nscogbuild/unixbuild/bld/mvm
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # Some gcc versions create a broken VM using -O2
 case `gcc -v 2>&1 | grep version | sed 's/gcc version *//'` in
 3.4.*)	OPT=-O1;;
@@ -11,3 +11,24 @@ rm -rf ../../../nsvmlinux
 # would prefer make install prefix=`readlink -f \`pwd\`/../../../nsvmlinux`
 # but older linux readlinks lack the -f flag
 make install prefix=`(cd ../../../;pwd)`/nsvmlinux
+(cd ../../../nsvmlinux
+ if [ -f squeak ]; then
+        mv squeak nsvm
+        ex -u NONE "+g/squeak/s/squeak/nsvm/g" +w +q nsvm
+  fi
+  if [ -f bin/squeak ]; then
+        mv bin/squeak bin/nsvm
+        ex -u NONE "+g/squeak/s/squeak/nsvm/g" +w +q bin/nsvm
+  fi
+  rm -rf man doc
+  LIBDIR="`echo lib/squeak/[0-9.-]*`"
+  test -f $LIBDIR/squeak && mv $LIBDIR/squeak $LIBDIR/nsvm
+  test -d lib/squeak && mv lib/squeak lib/nsvm
+  LIBDIR="`echo lib/nsvm/[0-9.-]*`"
+  if [ -h ~/Squeak/SqueakV41.sources ]; then
+	ln "`readlink ~/Squeak/SqueakV41.sources`" $LIBDIR
+  elif [ -f ~/Squeak/SqueakV41.sources ]; then
+	ln ~/Squeak/SqueakV41.sources $LIBDIR
+  else
+	echo "can't find SqueakV41.sources" 1>&2
+  fi)
