Cope with old linuxes use of /lib/tls hack for an optional thread-local-storage version of libc/libpthread. The launch scripts add /lib/tls:/usr/lib/tls: to LD_LIBRARY_PATH instead of /lib:/usr/lib: if the VM is linked to /lib/tls/libc.
git-svn-id: http://squeakvm.org/svn/squeak/branches/Cog@2518 fa1542d4-bde8-0310-ad64-8ed1123d492a

Former-commit-id: 5824163eef39e89d0ebc1d14f631f921232f9650

diff --git a/platforms/unix/config/bin.squeak.sh.in b/platforms/unix/config/bin.squeak.sh.in
--- a/platforms/unix/config/bin.squeak.sh.in
+++ b/platforms/unix/config/bin.squeak.sh.in
@@ -10,7 +10,15 @@ case "$BIN" in
 /*) PLUGINS="$BIN";;
 *) PLUGINS="`pwd`/$BIN"
 esac
+# On some old linuxes there is a /lib/tls thread-local-storage version of the C
+# library which the VM may use and if so should take precedence over /lib libc.
+case `/usr/bin/ldd "$BIN/squeak" | /bin/fgrep /libc. | sed 's/^.*=> //'` in
+/lib/tls/libc*)	SVMLLP="/lib/tls:/lib:/usr/lib/tls:/usr/lib";;
+/lib/libc*)		SVMLLP="/lib:/usr/lib";;
+*)				echo "can't infer base LD_LIBRARY_PATH. Aborting." 1>&2;
+				exit 1
+esac
 # prepending is less flexible but safer because it ensures we find the plugins
 # in the same directory as the VM.  We must include at least /lib and /usr/lib
 # if libraries there-in are to be found.  These directories are not implicit.
-LD_LIBRARY_PATH=$PLUGINS:${LD_LIBRARY_PATH:-/lib:/usr/lib} exec "$BIN/squeak" "$@"
+LD_LIBRARY_PATH=$PLUGINS:$SVMLLP:${LD_LIBRARY_PATH} exec "$BIN/squeak" "$@"
