Add yet another libc line to the linux launch script(s), and try and make the script suggest users extend it themselves.  you can lead a horse to water... Rationalize the includes in sqUnixUUID.c.
git-svn-id: http://squeakvm.org/svn/squeak/branches/Cog@2661 fa1542d4-bde8-0310-ad64-8ed1123d492a

Former-commit-id: 69a07c1410aefabd321feaa7a044657fccdae4db

diff --git a/platforms/unix/config/squeak.sh.in b/platforms/unix/config/squeak.sh.in
--- a/platforms/unix/config/squeak.sh.in
+++ b/platforms/unix/config/squeak.sh.in
@@ -14,15 +14,18 @@ esac
 # libc (e.g. through the FFI) then it must use the same version that the VM uses
 # and so it should take precedence over /lib libc.  This is done by setting
 # LD_LIBRARY_PATH appropriately, based on ldd's idea of the libc use by the VM.
-case `/usr/bin/ldd "$BIN/squeak" | /bin/fgrep /libc. | sed 's/^.*=> //'` in
+LIBC_SO="`/usr/bin/ldd "$BIN/squeak" | /bin/fgrep /libc. | sed 's/^.*=> //'`"
+case "$LIBC_SO" in
 /lib/libc*)					SVMLLP="/lib:/usr/lib";;
 /lib32/libc*)				SVMLLP="/lib32:/usr/lib32";;
 /lib64/libc*)				SVMLLP="/lib64:/usr/lib64";;
 /lib/tls/libc*)				SVMLLP="/lib/tls:/lib:/usr/lib/tls:/usr/lib";;
 /lib/i386-linux-gnu/libc*)	\
-	SVMLLP="/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu";;
+	SVMLLP="/lib/i386-linux-gnu:/lib:/usr/lib/i386-linux-gnu:/usr/lib";;
 /lib/tls/i686/cmov/libc*)	\
 	SVMLLP="/lib/tls/i686/cmov:/lib:/usr/lib/tls/i686/cmov:/usr/lib";;
+/lib/386-linux-gnu/i686/cmov/libc*)	\
+	SVMLLP="/lib/386-linux-gnu/i686/cmov:/lib:/usr/lib/386-linux-gnu/i686/cmov:/usr/lib";;
 /lib/tls/i686/nosegneg/libc*)	\
 	SVMLLP="/lib/i686/nosegneg/tls:/lib:/usr/lib/i686/nosegneg/tls:/usr/lib";;
 "")	case `/bin/uname -m || /usr/bin/uname -m` in
@@ -30,7 +33,7 @@ case `/usr/bin/ldd "$BIN/squeak" | /bin/fgrep /libc. | sed 's/^.*=> //'` in
 	*)	echo "/usr/bin/ldd didn't produce any output. Can't infer base LD_LIBRARY_PATH. Aborting." 1>&2
 	esac
 	exit 1;;
-*)	echo "Can't infer base LD_LIBRARY_PATH. Aborting." 1>&2
+*)	echo "Can't infer base LD_LIBRARY_PATH. Aborting. Try adding a line for $LIBC_SO to $0. Please report your edit to squeak vm-dev." 1>&2
 	exit 1
 esac
 # prepending is less flexible but safer because it ensures we find the plugins
